# Generated by Django 4.1.5 on 2023-01-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_candidate_hr_score_alter_candidate_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'can export candidate list')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
