# Generated by Django 4.1.5 on 2023-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
